/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.24
 * Generated at: 2024-09-22 05:20:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class forget_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/E:/workspace-spring-tool-suite/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/LaptrinhData/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_2.tld", Long.valueOf(1664428278000L));
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1724834644964L));
    _jspx_dependants.put("/common/web/footer.jsp", Long.valueOf(1726643184715L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>Login | Metronic Frontend</title>\r\n");
      out.write("\r\n");
      out.write("<meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("\r\n");
      out.write("<meta content=\"Metronic Shop UI description\" name=\"description\">\r\n");
      out.write("<meta content=\"Metronic Shop UI keywords\" name=\"keywords\">\r\n");
      out.write("<meta content=\"keenthemes\" name=\"author\">\r\n");
      out.write("\r\n");
      out.write("<meta property=\"og:site_name\" content=\"-CUSTOMER VALUE-\">\r\n");
      out.write("<meta property=\"og:title\" content=\"-CUSTOMER VALUE-\">\r\n");
      out.write("<meta property=\"og:description\" content=\"-CUSTOMER VALUE-\">\r\n");
      out.write("<meta property=\"og:type\" content=\"website\">\r\n");
      out.write("<meta property=\"og:image\" content=\"-CUSTOMER VALUE-\">\r\n");
      out.write("<!-- link to image for socio -->\r\n");
      out.write("<meta property=\"og:url\" content=\"-CUSTOMER VALUE-\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("<!-- Fonts START -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700|PT+Sans+Narrow|Source+Sans+Pro:200,300,400,600,700,900&amp;subset=all\"\r\n");
      out.write("	rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<!-- Fonts END -->\r\n");
      out.write("\r\n");
      out.write("<!-- Global styles START -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/global/plugins/font-awesome/css/font-awesome.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/global/plugins/bootstrap/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<!-- Global styles END -->\r\n");
      out.write("\r\n");
      out.write("<!-- Page level plugin styles START -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/global/plugins/fancybox/source/jquery.fancybox.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/global/plugins/uniform/css/uniform.default.css\"\r\n");
      out.write("	rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<!-- Page level plugin styles END -->\r\n");
      out.write("\r\n");
      out.write("<!-- Theme styles START -->\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/global/css/components.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/layout/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/layout/css/style-responsive.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/layout/css/themes/red.css\"\r\n");
      out.write("	rel=\"stylesheet\" id=\"style-color\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/layout/css/custom.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<!-- Theme styles END -->\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- BEGIN TOP BAR -->\r\n");
      out.write("<div class=\"pre-header\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<!-- BEGIN TOP BAR LEFT PART -->\r\n");
      out.write("			<div class=\"col-md-6 col-sm-6 additional-shop-info\">\r\n");
      out.write("				<ul class=\"list-unstyled list-inline\">\r\n");
      out.write("					<li><i class=\"fa fa-phone\"></i><span>+1 456 6717</span></li>\r\n");
      out.write("					<!-- BEGIN CURRENCIES -->\r\n");
      out.write("					<li class=\"shop-currencies\"><a href=\"javascript:void(0);\">€</a>\r\n");
      out.write("						<a href=\"javascript:void(0);\">£</a> <a href=\"javascript:void(0);\"\r\n");
      out.write("						class=\"current\">$</a></li>\r\n");
      out.write("					<!-- END CURRENCIES -->\r\n");
      out.write("					<!-- BEGIN LANGS -->\r\n");
      out.write("					<li class=\"langs-block\"><a href=\"javascript:void(0);\"\r\n");
      out.write("						class=\"current\">English </a>\r\n");
      out.write("						<div class=\"langs-block-others-wrapper\">\r\n");
      out.write("							<div class=\"langs-block-others\">\r\n");
      out.write("								<a href=\"javascript:void(0);\">French</a> <a\r\n");
      out.write("									href=\"javascript:void(0);\">Germany</a> <a\r\n");
      out.write("									href=\"javascript:void(0);\">Turkish</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div></li>\r\n");
      out.write("					<!-- END LANGS -->\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- END TOP BAR LEFT PART -->\r\n");
      out.write("			<!-- BEGIN TOP BAR MENU -->\r\n");
      out.write("			<div class=\"col-md-6 col-sm-6 additional-nav\">\r\n");
      out.write("				<ul class=\"list-unstyled list-inline pull-right\">\r\n");
      out.write("					<li><a href=\"shop-account.html\">My Account</a></li>\r\n");
      out.write("					<li><a href=\"shop-wishlist.html\">My Wishlist</a></li>\r\n");
      out.write("					<li><a href=\"shop-checkout.html\">Checkout</a></li>\r\n");
      out.write("					<li><a href=\"/LaptrinhData/login\">Log In</a></li>\r\n");
      out.write("					<li><a href=\"/LaptrinhData/register\">Register</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- END TOP BAR MENU -->\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- END TOP BAR -->\r\n");
      out.write("\r\n");
      out.write("<!-- BEGIN HEADER -->\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<a class=\"site-logo\" href=\"shop-index.html\"><img\r\n");
      out.write("			src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/layout/img/logos/logo-shop-red.png\"\r\n");
      out.write("			alt=\"Metronic Shop UI\"></a> <a href=\"javascript:void(0);\"\r\n");
      out.write("			class=\"mobi-toggler\"><i class=\"fa fa-bars\"></i></a>\r\n");
      out.write("\r\n");
      out.write("		<!-- BEGIN CART -->\r\n");
      out.write("\r\n");
      out.write("		<!--END CART -->\r\n");
      out.write("\r\n");
      out.write("		<!-- BEGIN NAVIGATION -->\r\n");
      out.write("		<div class=\"header-navigation\">\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li class=\"dropdown\"><a class=\"dropdown-toggle\"\r\n");
      out.write("					data-toggle=\"dropdown\" data-target=\"#\" href=\"#\"> Woman </a> <!-- BEGIN DROPDOWN MENU -->\r\n");
      out.write("					<ul class=\"dropdown-menu\">\r\n");
      out.write("						<li class=\"dropdown-submenu\"><a href=\"shop-product-list.html\">Hi\r\n");
      out.write("								Tops <i class=\"fa fa-angle-right\"></i>\r\n");
      out.write("						</a>\r\n");
      out.write("							<ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("								<li><a href=\"shop-product-list.html\">Second Level Link</a></li>\r\n");
      out.write("								<li><a href=\"shop-product-list.html\">Second Level Link</a></li>\r\n");
      out.write("								<li class=\"dropdown-submenu\"><a class=\"dropdown-toggle\"\r\n");
      out.write("									data-toggle=\"dropdown\" data-target=\"#\" href=\"#\"> Second\r\n");
      out.write("										Level Link <i class=\"fa fa-angle-right\"></i>\r\n");
      out.write("								</a>\r\n");
      out.write("									<ul class=\"dropdown-menu\">\r\n");
      out.write("										<li><a href=\"shop-product-list.html\">Third Level Link</a></li>\r\n");
      out.write("										<li><a href=\"shop-product-list.html\">Third Level Link</a></li>\r\n");
      out.write("										<li><a href=\"shop-product-list.html\">Third Level Link</a></li>\r\n");
      out.write("									</ul></li>\r\n");
      out.write("							</ul></li>\r\n");
      out.write("						<li><a href=\"shop-product-list.html\">Running Shoes</a></li>\r\n");
      out.write("						<li><a href=\"shop-product-list.html\">Jackets and Coats</a></li>\r\n");
      out.write("					</ul> <!-- END DROPDOWN MENU --></li>\r\n");
      out.write("				<li class=\"dropdown dropdown-megamenu\"><a\r\n");
      out.write("					class=\"dropdown-toggle\" data-toggle=\"dropdown\" data-target=\"#\"\r\n");
      out.write("					href=\"#\"> Man </a>\r\n");
      out.write("					<ul class=\"dropdown-menu\">\r\n");
      out.write("						<li>\r\n");
      out.write("							<div class=\"header-navigation-content\">\r\n");
      out.write("								<div class=\"row\">\r\n");
      out.write("									<div class=\"col-md-4 header-navigation-col\">\r\n");
      out.write("										<h4>Footwear</h4>\r\n");
      out.write("										<ul>\r\n");
      out.write("											<li><a href=\"shop-product-list.html\">Astro Trainers</a></li>\r\n");
      out.write("											<li><a href=\"shop-product-list.html\">Basketball\r\n");
      out.write("													Shoes</a></li>\r\n");
      out.write("											<li><a href=\"shop-product-list.html\">Boots</a></li>\r\n");
      out.write("											<li><a href=\"shop-product-list.html\">Canvas Shoes</a></li>\r\n");
      out.write("											<li><a href=\"shop-product-list.html\">Football Boots</a></li>\r\n");
      out.write("											<li><a href=\"shop-product-list.html\">Golf Shoes</a></li>\r\n");
      out.write("											<li><a href=\"shop-product-list.html\">Hi Tops</a></li>\r\n");
      out.write("											<li><a href=\"shop-product-list.html\">Indoor and\r\n");
      out.write("													Court Trainers</a></li>\r\n");
      out.write("										</ul>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"col-md-4 header-navigation-col\">\r\n");
      out.write("										<h4>Clothing</h4>\r\n");
      out.write("										<ul>\r\n");
      out.write("											<li><a href=\"shop-product-list.html\">Base Layer</a></li>\r\n");
      out.write("											<li><a href=\"shop-product-list.html\">Character</a></li>\r\n");
      out.write("											<li><a href=\"shop-product-list.html\">Chinos</a></li>\r\n");
      out.write("											<li><a href=\"shop-product-list.html\">Combats</a></li>\r\n");
      out.write("											<li><a href=\"shop-product-list.html\">Cricket\r\n");
      out.write("													Clothing</a></li>\r\n");
      out.write("											<li><a href=\"shop-product-list.html\">Fleeces</a></li>\r\n");
      out.write("											<li><a href=\"shop-product-list.html\">Gilets</a></li>\r\n");
      out.write("											<li><a href=\"shop-product-list.html\">Golf Tops</a></li>\r\n");
      out.write("										</ul>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"col-md-4 header-navigation-col\">\r\n");
      out.write("										<h4>Accessories</h4>\r\n");
      out.write("										<ul>\r\n");
      out.write("											<li><a href=\"shop-product-list.html\">Belts</a></li>\r\n");
      out.write("											<li><a href=\"shop-product-list.html\">Caps</a></li>\r\n");
      out.write("											<li><a href=\"shop-product-list.html\">Gloves, Hats\r\n");
      out.write("													and Scarves</a></li>\r\n");
      out.write("										</ul>\r\n");
      out.write("\r\n");
      out.write("										<h4>Clearance</h4>\r\n");
      out.write("										<ul>\r\n");
      out.write("											<li><a href=\"shop-product-list.html\">Jackets</a></li>\r\n");
      out.write("											<li><a href=\"shop-product-list.html\">Bottoms</a></li>\r\n");
      out.write("										</ul>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"col-md-12 nav-brands\">\r\n");
      out.write("										<ul>\r\n");
      out.write("											<li><a href=\"shop-product-list.html\"><img\r\n");
      out.write("													title=\"esprit\" alt=\"esprit\"\r\n");
      out.write("													src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/brands/esprit.jpg\"></a></li>\r\n");
      out.write("											<li><a href=\"shop-product-list.html\"><img\r\n");
      out.write("													title=\"gap\" alt=\"gap\"\r\n");
      out.write("													src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/brands/gap.jpg\"></a></li>\r\n");
      out.write("											<li><a href=\"shop-product-list.html\"><img\r\n");
      out.write("													title=\"next\" alt=\"next\"\r\n");
      out.write("													src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/brands/next.jpg\"></a></li>\r\n");
      out.write("											<li><a href=\"shop-product-list.html\"><img\r\n");
      out.write("													title=\"puma\" alt=\"puma\"\r\n");
      out.write("													src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/brands/puma.jpg\"></a></li>\r\n");
      out.write("											<li><a href=\"shop-product-list.html\"><img\r\n");
      out.write("													title=\"zara\" alt=\"zara\"\r\n");
      out.write("													src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/brands/zara.jpg\"></a></li>\r\n");
      out.write("										</ul>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul></li>\r\n");
      out.write("				<li><a href=\"shop-item.html\">Kids</a></li>\r\n");
      out.write("				<li class=\"dropdown dropdown100 nav-catalogue\"><a\r\n");
      out.write("					class=\"dropdown-toggle\" data-toggle=\"dropdown\" data-target=\"#\"\r\n");
      out.write("					href=\"#\"> New </a>\r\n");
      out.write("					<ul class=\"dropdown-menu\">\r\n");
      out.write("						<li>\r\n");
      out.write("							<div class=\"header-navigation-content\">\r\n");
      out.write("								<div class=\"row\">\r\n");
      out.write("									<div class=\"col-md-3 col-sm-4 col-xs-6\">\r\n");
      out.write("										<div class=\"product-item\">\r\n");
      out.write("											<div class=\"pi-img-wrapper\">\r\n");
      out.write("												<a href=\"shop-item.html\"><img\r\n");
      out.write("													src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/model4.jpg\"\r\n");
      out.write("													class=\"img-responsive\" alt=\"Berry Lace Dress\"></a>\r\n");
      out.write("											</div>\r\n");
      out.write("											<h3>\r\n");
      out.write("												<a href=\"shop-item.html\">Berry Lace Dress</a>\r\n");
      out.write("											</h3>\r\n");
      out.write("											<div class=\"pi-price\">$29.00</div>\r\n");
      out.write("											<a href=\"#\" class=\"btn btn-default add2cart\">Add to cart</a>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"col-md-3 col-sm-4 col-xs-6\">\r\n");
      out.write("										<div class=\"product-item\">\r\n");
      out.write("											<div class=\"pi-img-wrapper\">\r\n");
      out.write("												<a href=\"shop-item.html\"><img\r\n");
      out.write("													src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/model3.jpg\"\r\n");
      out.write("													class=\"img-responsive\" alt=\"Berry Lace Dress\"></a>\r\n");
      out.write("											</div>\r\n");
      out.write("											<h3>\r\n");
      out.write("												<a href=\"shop-item.html\">Berry Lace Dress</a>\r\n");
      out.write("											</h3>\r\n");
      out.write("											<div class=\"pi-price\">$29.00</div>\r\n");
      out.write("											<a href=\"#\" class=\"btn btn-default add2cart\">Add to cart</a>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"col-md-3 col-sm-4 col-xs-6\">\r\n");
      out.write("										<div class=\"product-item\">\r\n");
      out.write("											<div class=\"pi-img-wrapper\">\r\n");
      out.write("												<a href=\"shop-item.html\"><img\r\n");
      out.write("													src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/model7.jpg\"\r\n");
      out.write("													class=\"img-responsive\" alt=\"Berry Lace Dress\"></a>\r\n");
      out.write("											</div>\r\n");
      out.write("											<h3>\r\n");
      out.write("												<a href=\"shop-item.html\">Berry Lace Dress</a>\r\n");
      out.write("											</h3>\r\n");
      out.write("											<div class=\"pi-price\">$29.00</div>\r\n");
      out.write("											<a href=\"#\" class=\"btn btn-default add2cart\">Add to cart</a>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"col-md-3 col-sm-4 col-xs-6\">\r\n");
      out.write("										<div class=\"product-item\">\r\n");
      out.write("											<div class=\"pi-img-wrapper\">\r\n");
      out.write("												<a href=\"shop-item.html\"><img\r\n");
      out.write("													src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/model4.jpg\"\r\n");
      out.write("													class=\"img-responsive\" alt=\"Berry Lace Dress\"></a>\r\n");
      out.write("											</div>\r\n");
      out.write("											<h3>\r\n");
      out.write("												<a href=\"shop-item.html\">Berry Lace Dress</a>\r\n");
      out.write("											</h3>\r\n");
      out.write("											<div class=\"pi-price\">$29.00</div>\r\n");
      out.write("											<a href=\"#\" class=\"btn btn-default add2cart\">Add to cart</a>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul></li>\r\n");
      out.write("				<li class=\"dropdown active\"><a class=\"dropdown-toggle\"\r\n");
      out.write("					data-toggle=\"dropdown\" data-target=\"#\" href=\"#\"> Pages </a>\r\n");
      out.write("\r\n");
      out.write("					<ul class=\"dropdown-menu\">\r\n");
      out.write("						<li><a href=\"shop-index.html\">Home Default</a></li>\r\n");
      out.write("						<li class=\"active\"><a href=\"shop-index-header-fix.html\">Home\r\n");
      out.write("								Header Fixed</a></li>\r\n");
      out.write("						<li><a href=\"shop-index-light-footer.html\">Home Light\r\n");
      out.write("								Footer</a></li>\r\n");
      out.write("						<li><a href=\"shop-product-list.html\">Product List</a></li>\r\n");
      out.write("						<li><a href=\"shop-search-result.html\">Search Result</a></li>\r\n");
      out.write("						<li><a href=\"shop-item.html\">Product Page</a></li>\r\n");
      out.write("						<li><a href=\"shop-shopping-cart-null.html\">Shopping Cart\r\n");
      out.write("								(Null Cart)</a></li>\r\n");
      out.write("						<li><a href=\"shop-shopping-cart.html\">Shopping Cart</a></li>\r\n");
      out.write("						<li><a href=\"shop-checkout.html\">Checkout</a></li>\r\n");
      out.write("						<li><a href=\"shop-about.html\">About</a></li>\r\n");
      out.write("						<li><a href=\"shop-contacts.html\">Contacts</a></li>\r\n");
      out.write("						<li><a href=\"shop-account.html\">My account</a></li>\r\n");
      out.write("						<li><a href=\"shop-wishlist.html\">My Wish List</a></li>\r\n");
      out.write("						<li><a href=\"shop-goods-compare.html\">Product Comparison</a></li>\r\n");
      out.write("						<li><a href=\"shop-standart-forms.html\">Standart Forms</a></li>\r\n");
      out.write("						<li><a href=\"shop-faq.html\">FAQ</a></li>\r\n");
      out.write("						<li><a href=\"shop-privacy-policy.html\">Privacy Policy</a></li>\r\n");
      out.write("						<li><a href=\"shop-terms-conditions-page.html\">Terms &amp;\r\n");
      out.write("								Conditions</a></li>\r\n");
      out.write("					</ul></li>\r\n");
      out.write("				<li><a href=\"index.html\" target=\"_blank\">Corporate</a></li>\r\n");
      out.write("				<li><a href=\"onepage-index.html\" target=\"_blank\">One Page</a></li>\r\n");
      out.write("				<li><a\r\n");
      out.write("					href=\"http://keenthemes.com/preview/metronic/theme/templates/admin&amp;page=ecommerce_index.html\"\r\n");
      out.write("					target=\"_blank\">Admin theme</a></li>\r\n");
      out.write("\r\n");
      out.write("				<!-- BEGIN TOP SEARCH -->\r\n");
      out.write("				<li class=\"menu-search\"><span class=\"sep\"></span> <i\r\n");
      out.write("					class=\"fa fa-search search-btn\"></i>\r\n");
      out.write("					<div class=\"search-box\">\r\n");
      out.write("						<form action=\"#\">\r\n");
      out.write("							<div class=\"input-group\">\r\n");
      out.write("								<input type=\"text\" placeholder=\"Search\" class=\"form-control\">\r\n");
      out.write("								<span class=\"input-group-btn\">\r\n");
      out.write("									<button class=\"btn btn-primary\" type=\"submit\">Search</button>\r\n");
      out.write("								</span>\r\n");
      out.write("							</div>\r\n");
      out.write("						</form>\r\n");
      out.write("					</div></li>\r\n");
      out.write("				<!-- END TOP SEARCH -->\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- END NAVIGATION -->\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Header END -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"main\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<ul class=\"breadcrumb\">\r\n");
      out.write("			<li><a href=\"thuc.jsp\">Home</a></li>\r\n");
      out.write("			<li><a href=\"#\">Pages</a></li>\r\n");
      out.write("			<li class=\"active\">Login</li>\r\n");
      out.write("		</ul>\r\n");
      out.write("		<!-- BEGIN SIDEBAR & CONTENT -->\r\n");
      out.write("		<div class=\"row margin-bottom-40\">\r\n");
      out.write("			<!-- BEGIN SIDEBAR -->\r\n");
      out.write("			<div class=\"sidebar col-md-3 col-sm-3\">\r\n");
      out.write("				<ul class=\"list-group margin-bottom-25 sidebar-menu\">\r\n");
      out.write("					<li class=\"list-group-item clearfix\"><a href=\"#\"><i\r\n");
      out.write("							class=\"fa fa-angle-right\"></i> Login/Register</a></li>\r\n");
      out.write("					<li class=\"list-group-item clearfix\"><a href=\"#\"><i\r\n");
      out.write("							class=\"fa fa-angle-right\"></i> Restore Password</a></li>\r\n");
      out.write("					<li class=\"list-group-item clearfix\"><a href=\"#\"><i\r\n");
      out.write("							class=\"fa fa-angle-right\"></i> My account</a></li>\r\n");
      out.write("					<li class=\"list-group-item clearfix\"><a href=\"#\"><i\r\n");
      out.write("							class=\"fa fa-angle-right\"></i> Address book</a></li>\r\n");
      out.write("					<li class=\"list-group-item clearfix\"><a href=\"#\"><i\r\n");
      out.write("							class=\"fa fa-angle-right\"></i> Wish list</a></li>\r\n");
      out.write("					<li class=\"list-group-item clearfix\"><a href=\"#\"><i\r\n");
      out.write("							class=\"fa fa-angle-right\"></i> Returns</a></li>\r\n");
      out.write("					<li class=\"list-group-item clearfix\"><a href=\"#\"><i\r\n");
      out.write("							class=\"fa fa-angle-right\"></i> Newsletter</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- END SIDEBAR -->\r\n");
      out.write("\r\n");
      out.write("			<!-- BEGIN CONTENT -->\r\n");
      out.write("			<div class=\"col-md-9 col-sm-9\">\r\n");
      out.write("\r\n");
      out.write("				<h1>Login</h1>\r\n");
      out.write("				<div class=\"content-form-page\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col-md-7 col-sm-7\">\r\n");
      out.write("							<form class=\"form-horizontal form-without-legend\" role=\"form\"\r\n");
      out.write("								action=\"/LaptrinhData/forget\" method=\"post\">\r\n");
      out.write("								");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("								<div class=\"form-group\">\r\n");
      out.write("									<label for=\"username\" class=\"col-lg-4 control-label\">Username\r\n");
      out.write("										<span class=\"require\">*</span>\r\n");
      out.write("									</label>\r\n");
      out.write("									<div class=\"col-lg-8\">\r\n");
      out.write("										<input type=\"text\" class=\"form-control\" id=\"username\"\r\n");
      out.write("											name=\"username\">\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"form-group\">\r\n");
      out.write("									<label for=\"password\" class=\"col-lg-4 control-label\">New Password\r\n");
      out.write("										<span class=\"require\">*</span>\r\n");
      out.write("									</label>\r\n");
      out.write("									<div class=\"col-lg-8\">\r\n");
      out.write("										<input type=\"text\" class=\"form-control\" id=\"password\"\r\n");
      out.write("											name=\"password\">\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"form-group\">\r\n");
      out.write("									<label for=\"password\" class=\"col-lg-4 control-label\">Re-enter Password\r\n");
      out.write("										<span class=\"require\">*</span>\r\n");
      out.write("									</label>\r\n");
      out.write("									<div class=\"col-lg-8\">\r\n");
      out.write("										<input type=\"text\" class=\"form-control\" id=\"password\"\r\n");
      out.write("											name=\"npassword\">\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"row\">\r\n");
      out.write("									<div\r\n");
      out.write("										class=\"col-lg-8 col-md-offset-4 padding-left-0 padding-top-20\">\r\n");
      out.write("										<button type=\"submit\" class=\"btn btn-primary\">Accecpt</button>\r\n");
      out.write("										<input type=\"button\" class=\"btn btn-primary\" value=\"Login\" onclick=\"redirectToLogin()\">\r\n");
      out.write("										<input type=\"button\" class=\"btn btn-primary\" value=\"Register\" onclick=\"redirectToRegister()\">									\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								\r\n");
      out.write("								<div class=\"row\">\r\n");
      out.write("									<div\r\n");
      out.write("										class=\"col-lg-8 col-md-offset-4 padding-left-0 padding-top-10 padding-right-30\">\r\n");
      out.write("										<hr>\r\n");
      out.write("										<div class=\"login-socio\">\r\n");
      out.write("											<p class=\"text-muted\">or login using:</p>\r\n");
      out.write("											<ul class=\"social-icons\">\r\n");
      out.write("												<li><a href=\"#\" data-original-title=\"facebook\"\r\n");
      out.write("													class=\"facebook\" title=\"facebook\"></a></li>\r\n");
      out.write("												<li><a href=\"#\" data-original-title=\"Twitter\"\r\n");
      out.write("													class=\"twitter\" title=\"Twitter\"></a></li>\r\n");
      out.write("												<li><a href=\"#\" data-original-title=\"Google Plus\"\r\n");
      out.write("													class=\"googleplus\" title=\"Google Plus\"></a></li>\r\n");
      out.write("												<li><a href=\"#\" data-original-title=\"Linkedin\"\r\n");
      out.write("													class=\"linkedin\" title=\"LinkedIn\"></a></li>\r\n");
      out.write("											</ul>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</form>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-md-4 col-sm-4 pull-right\">\r\n");
      out.write("							<div class=\"form-info\">\r\n");
      out.write("								<h2>\r\n");
      out.write("									<em>Important</em> Information\r\n");
      out.write("								</h2>\r\n");
      out.write("								<p>Duis autem vel eum iriure at dolor vulputate velit esse\r\n");
      out.write("									vel molestie at dolore.</p>\r\n");
      out.write("\r\n");
      out.write("								<button type=\"button\" class=\"btn btn-default\">More\r\n");
      out.write("									details</button>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- END CONTENT -->\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- END SIDEBAR & CONTENT -->\r\n");
      out.write("	</div>\r\n");
      out.write("	<!--  BEGIN FOOTER -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	    <!-- BEGIN STEPS -->\r\n");
      out.write("    <div class=\"steps-block steps-block-red\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-4 steps-block-col\">\r\n");
      out.write("            <i class=\"fa fa-truck\"></i>\r\n");
      out.write("            <div>\r\n");
      out.write("              <h2>Free shipping</h2>\r\n");
      out.write("              <em>Express delivery withing 3 days</em>\r\n");
      out.write("            </div>\r\n");
      out.write("            <span>&nbsp;</span>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4 steps-block-col\">\r\n");
      out.write("            <i class=\"fa fa-gift\"></i>\r\n");
      out.write("            <div>\r\n");
      out.write("              <h2>Daily Gifts</h2>\r\n");
      out.write("              <em>3 Gifts daily for lucky customers</em>\r\n");
      out.write("            </div>\r\n");
      out.write("            <span>&nbsp;</span>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4 steps-block-col\">\r\n");
      out.write("            <i class=\"fa fa-phone\"></i>\r\n");
      out.write("            <div>\r\n");
      out.write("              <h2>477 505 8877</h2>\r\n");
      out.write("              <em>24/7 customer care available</em>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- END STEPS -->\r\n");
      out.write("\r\n");
      out.write("    <!-- BEGIN PRE-FOOTER -->\r\n");
      out.write("    <div class=\"pre-footer\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <!-- BEGIN BOTTOM ABOUT BLOCK -->\r\n");
      out.write("          <div class=\"col-md-3 col-sm-6 pre-footer-col\">\r\n");
      out.write("            <h2>About us</h2>\r\n");
      out.write("            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam sit nonummy nibh euismod tincidunt ut laoreet dolore magna aliquarm erat sit volutpat. Nostrud exerci tation ullamcorper suscipit lobortis nisl aliquip  commodo consequat. </p>\r\n");
      out.write("            <p>Duis autem vel eum iriure dolor vulputate velit esse molestie at dolore.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- END BOTTOM ABOUT BLOCK -->\r\n");
      out.write("          <!-- BEGIN BOTTOM INFO BLOCK -->\r\n");
      out.write("          <div class=\"col-md-3 col-sm-6 pre-footer-col\">\r\n");
      out.write("            <h2>Information</h2>\r\n");
      out.write("            <ul class=\"list-unstyled\">\r\n");
      out.write("              <li><i class=\"fa fa-angle-right\"></i> <a href=\"#\">Delivery Information</a></li>\r\n");
      out.write("              <li><i class=\"fa fa-angle-right\"></i> <a href=\"#\">Customer Service</a></li>\r\n");
      out.write("              <li><i class=\"fa fa-angle-right\"></i> <a href=\"#\">Order Tracking</a></li>\r\n");
      out.write("              <li><i class=\"fa fa-angle-right\"></i> <a href=\"#\">Shipping &amp; Returns</a></li>\r\n");
      out.write("              <li><i class=\"fa fa-angle-right\"></i> <a href=\"contacts.html\">Contact Us</a></li>\r\n");
      out.write("              <li><i class=\"fa fa-angle-right\"></i> <a href=\"#\">Careers</a></li>\r\n");
      out.write("              <li><i class=\"fa fa-angle-right\"></i> <a href=\"#\">Payment Methods</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- END INFO BLOCK -->\r\n");
      out.write("\r\n");
      out.write("          <!-- BEGIN TWITTER BLOCK --> \r\n");
      out.write("          <div class=\"col-md-3 col-sm-6 pre-footer-col\">\r\n");
      out.write("            <h2 class=\"margin-bottom-0\">Latest Tweets</h2>\r\n");
      out.write("            <a class=\"twitter-timeline\" href=\"https://twitter.com/twitterapi\" data-tweet-limit=\"2\" data-theme=\"dark\" data-link-color=\"#57C8EB\" data-widget-id=\"455411516829736961\" data-chrome=\"noheader nofooter noscrollbar noborders transparent\">Loading tweets by @keenthemes...</a>      \r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- END TWITTER BLOCK -->\r\n");
      out.write("\r\n");
      out.write("          <!-- BEGIN BOTTOM CONTACTS -->\r\n");
      out.write("          <div class=\"col-md-3 col-sm-6 pre-footer-col\">\r\n");
      out.write("            <h2>Our Contacts</h2>\r\n");
      out.write("            <address class=\"margin-bottom-40\">\r\n");
      out.write("              35, Lorem Lis Street, Park Ave<br>\r\n");
      out.write("              California, US<br>\r\n");
      out.write("              Phone: 300 323 3456<br>\r\n");
      out.write("              Fax: 300 323 1456<br>\r\n");
      out.write("              Email: <a href=\"mailto:info@metronic.com\">info@metronic.com</a><br>\r\n");
      out.write("              Skype: <a href=\"skype:metronic\">metronic</a>\r\n");
      out.write("            </address>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- END BOTTOM CONTACTS -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <hr>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <!-- BEGIN SOCIAL ICONS -->\r\n");
      out.write("          <div class=\"col-md-6 col-sm-6\">\r\n");
      out.write("            <ul class=\"social-icons\">\r\n");
      out.write("              <li><a class=\"rss\" data-original-title=\"rss\" href=\"#\"></a></li>\r\n");
      out.write("              <li><a class=\"facebook\" data-original-title=\"facebook\" href=\"#\"></a></li>\r\n");
      out.write("              <li><a class=\"twitter\" data-original-title=\"twitter\" href=\"#\"></a></li>\r\n");
      out.write("              <li><a class=\"googleplus\" data-original-title=\"googleplus\" href=\"#\"></a></li>\r\n");
      out.write("              <li><a class=\"linkedin\" data-original-title=\"linkedin\" href=\"#\"></a></li>\r\n");
      out.write("              <li><a class=\"youtube\" data-original-title=\"youtube\" href=\"#\"></a></li>\r\n");
      out.write("              <li><a class=\"vimeo\" data-original-title=\"vimeo\" href=\"#\"></a></li>\r\n");
      out.write("              <li><a class=\"skype\" data-original-title=\"skype\" href=\"#\"></a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- END SOCIAL ICONS -->\r\n");
      out.write("          <!-- BEGIN NEWLETTER -->\r\n");
      out.write("          <div class=\"col-md-6 col-sm-6\">\r\n");
      out.write("            <div class=\"pre-footer-subscribe-box pull-right\">\r\n");
      out.write("              <h2>Newsletter</h2>\r\n");
      out.write("              <form action=\"#\">\r\n");
      out.write("                <div class=\"input-group\">\r\n");
      out.write("                  <input type=\"text\" placeholder=\"youremail@mail.com\" class=\"form-control\">\r\n");
      out.write("                  <span class=\"input-group-btn\">\r\n");
      out.write("                    <button class=\"btn btn-primary\" type=\"submit\">Subscribe</button>\r\n");
      out.write("                  </span>\r\n");
      out.write("                </div>\r\n");
      out.write("              </form>\r\n");
      out.write("            </div> \r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- END NEWLETTER -->\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- END PRE-FOOTER -->\r\n");
      out.write("\r\n");
      out.write("	<!--  END FOOTER -->\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("    function redirectToRegister() {\r\n");
      out.write("        // Chuyển hướng đến trang đăng ký\r\n");
      out.write("        window.location.href = \"/LaptrinhData/register\"; // Thay đổi URL đến trang JSP bạn muốn mở\r\n");
      out.write("    }\r\n");
      out.write("    function redirectToLogin() {\r\n");
      out.write("        // Chuyển hướng đến trang đăng ký\r\n");
      out.write("        window.location.href = \"/LaptrinhData/login\"; // Thay đổi URL đến trang JSP bạn muốn mở\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /views/forget.jsp(4,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/");
      // /views/forget.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setVar("URL");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /views/forget.jsp(379,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${alert !=null}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("									<h3 class=\"alert alertdanger\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${alert}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</h3>\r\n");
          out.write("								");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
